# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qFfbwro3MRG8m3Hssywoe1fwVWgCB16
"""

from sklearn.linear_model import LinearRegression
import numpy as np

# Relações presentes na tabela
tempoDeViagem = np.array([[9], [5], [8.5], [6.2], [4.5], [6.7], [7.5], [6.1]])
pacotesEntregues = np.array([[5], [4], [5], [3], [2], [2], [4], [3]])
distanciasPercorrida = np.array([[98], [55], [98], [99], [52], [76], [79], [64]])

# Criação do modelo de Regressão
modeloRegressao = LinearRegression()

# Treinando o modelo com os dados de treinamento
modeloRegressao.fit(np.hstack((distanciasPercorrida, pacotesEntregues)), tempoDeViagem)

# Fazendo previsões para uma distância de 70 e 6 pacotes a serem entregues
distanciaTeste = np.array([[70, 6]])
tempoEstimado = modeloRegressao.predict(distanciaTeste)

print("O tempo para uma distância para 70 e 6 pacotes, dura em média ", tempoEstimado)

